#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 http://www.youtube.com/;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
