#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo touch /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i '/server_name _;/a \\n\tlocation  /redirect_me {\n\t\treturn 301 http://www.example.com/;\n\t}' /etc/nginx/sites-available/default
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default
service nginx restart
